# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='firstname',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lastname',
            field=models.TextField(max_length=20),
        ),
    ]
