# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0003_auto_20171003_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profilephoto',
            field=models.ImageField(blank=True, default='/static/images/images.png', upload_to=b''),
        ),
    ]
