# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0006_auto_20171007_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='post-photos'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilephoto',
            field=models.ImageField(blank=True, default='images.png', upload_to='profile-photos'),
        ),
    ]
