# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0007_auto_20171007_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profilephoto',
            field=models.ImageField(blank=True, default='profile-photos/images.png', upload_to='profile-photos'),
        ),
    ]
