# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 23:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grumblr', '0008_auto_20171007_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='followed',
            field=models.ManyToManyField(related_name='followed', to=settings.AUTH_USER_MODEL),
        ),
    ]
