# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 16:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0002_auto_20170919_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='url',
            field=models.URLField(default='#'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
