# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0003_auto_20170919_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='userprofilephoto',
            field=models.ImageField(default='/static/images/images.png', upload_to=b''),
        ),
    ]
