# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0004_post_userprofilephoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='userprofilephoto',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilephoto',
            field=models.ImageField(default='/static/images/images.png', upload_to=b''),
        ),
    ]
